### ISSUE TITLE
程序卡死？

### ISSUE THREAD

**Issue by a88wyzz** [sakuraakira/AniGamerDownloader#1]
![QQ截图20190718211937](https://user-images.githubusercontent.com/35162785/61460751-fc588800-a9a1-11e9-8e60-919a67bb8200.jpg)

![QQ截图20190718212051](https://user-images.githubusercontent.com/35162785/61460753-fcf11e80-a9a1-11e9-980a-b7130c804fee.jpg)

不论是复制网址，还是填写SN都是卡死，系统win10，ffmpeg已放入文件夹中，还有没有设定代理选项？

**Comment by sakuraakira** [comment]
是不是沒有啟用 .NET 呢?
需要.NET4.6 以上版本~ WIN10有自帶.NET4.7 或許是被關掉
Proxy伺服器功能 考慮中

**Comment by a88wyzz** [comment]
win10自带.net 4.6默认是启用的，请从控制面板--程序和功能--启动或关闭windows功能  查看
不存在.net 问题，用过很多.net程序都没有问题的
![QQ截图20190718223932](https://user-images.githubusercontent.com/35162785/61466692-ef8d6180-a9ac-11e9-881b-b92ccab28b3e.jpg)

**Comment by sakuraakira** [comment]
可以的話 能否提供錯誤事件的描述?
![1563460967445](https://user-images.githubusercontent.com/18613058/61466972-6aef1300-a9ad-11e9-8550-3cb99886101c.jpg)

**Comment by a88wyzz** [comment]
[error.txt](https://github.com/sakuraakira/AniGamerDownloader/files/3407080/error.txt)
错误事件保存为txt文件了

**Comment by sakuraakira** [comment]
感謝回報，關於System.Net.Sockets.SocketException的錯誤，大致上是連線的問題 ex:禁止訪問等等的。下個版本會針對這個錯誤出現時，提示更詳細的錯誤內容。
海外IP使用Proxy才有辨法下載，使用這種連線方式很容易斷線。所以資料必需支援暫存及重新連線，此功能需要一點時間。

**Comment by sakuraakira** [comment]
新功能上架囉　再看看有什麼問題吧
